const data = {
    questions: {
        skin: [
            { id: 'skin_feel', text: 'How does your skin feel right after washing?', options: [{ id: 'feel_dry', label: 'Tight and Dry', points: { dry: 2, sensitive: 1, oily: -1 } }, { id: 'feel_normal', label: 'Comfortable', points: { normal: 2 } }, { id: 'feel_oily', label: 'Instantly Oily', points: { oily: 2, dry: -2 } }] },
            { id: 'skin_appearance', text: 'How does your skin look by midday?', options: [{ id: 'app_flaky', label: 'Flaky or Dull', points: { dry: 2, dullness: 1 } }, { id: 'app_normal', label: 'Mostly fine', points: { normal: 2 } }, { id: 'app_shiny', label: 'Shiny/Oily', points: { oily: 2, acne: 1 } }] },
            { id: 'skin_concern', text: 'What is your primary skin concern?', options: [{ id: 'conc_acne', label: 'Acne & Breakouts', points: { acne: 3, oily: 1 } }, { id: 'conc_aging', label: 'Fine Lines & Aging', points: { aging: 3, dry: 1 } }, { id: 'conc_dull', label: 'Dullness & Uneven Tone', points: { dullness: 3, pigmentation: 1 } }, { id: 'conc_dry', label: 'Severe Dryness', points: { dry: 3, sensitive: 1 } }, { id: 'conc_red', label: 'Redness & Sensitivity', points: { sensitive: 3, redness: 2 } }] },
            { id: 'skin_texture', text: 'If you look in the mirror closely, what best describes your skin texture?', options: [{ id: 'text_smooth', label: 'Smooth and even', points: { normal: 2 } }, { id: 'text_pores', label: 'Visible/enlarged pores', points: { oily: 2, acne: 1 } }, { id: 'text_rough', label: 'Rough and bumpy', points: { textured: 3, dry: 1 } }] },
            { id: 'skin_sensitivity', text: 'How often do your skincare products cause irritation or stinging?', options: [{ id: 'sens_rare', label: 'Rarely / Never', points: { sensitive: -2 } }, { id: 'sens_sometimes', label: 'Sometimes', points: { sensitive: 1 } }, { id: 'sens_often', label: 'Often', points: { sensitive: 3, redness: 1 } }] },
            { id: 'skin_product_type', text: 'What type of product do you want to add to your routine?', options: [{ id: 'type_cleanser', label: 'Cleanser', filterTarget: 'Cleanser' }, { id: 'type_serum', label: 'Serum / Treatment', filterTarget: 'Serum' }, { id: 'type_moisturizer', label: 'Moisturizer', filterTarget: 'Moisturizer' }, { id: 'type_spf', label: 'Sunscreen', filterTarget: 'Sunscreen' }, { id: 'type_any', label: 'Show me everything', filterTarget: 'All' }] }
        ],
        hair: [
            { id: 'hair_type', text: 'How would you describe your natural hair texture?', options: [{ id: 'ht_straight', label: 'Straight (Type 1)', points: { straight: 2, volume: 1 } }, { id: 'ht_wavy', label: 'Wavy (Type 2)', points: { wavy: 2, frizz: 1 } }, { id: 'ht_curly', label: 'Curly (Type 3)', points: { curly: 2, dry: 1 } }, { id: 'ht_coily', label: 'Coily (Type 4)', points: { coily: 2, dry: 2 } }] },
            { id: 'hair_scalp', text: 'What is your scalp type like?', options: [{ id: 'hs_oily', label: 'Gets oily very quickly', points: { scalp_oily: 3, volume: -1 } }, { id: 'hs_normal', label: 'Normal / Balanced', points: { scalp_normal: 2 } }, { id: 'hs_dry', label: 'Dry or Flaky', points: { scalp_dry: 3, sensitive: 1 } }] },
            { id: 'hair_concern', text: 'What is your primary hair concern right now?', options: [{ id: 'hc_frizz', label: 'Frizz & Flyaways', points: { frizz: 3, hydration: 1 } }, { id: 'hc_damage', label: 'Damage & Split Ends', points: { damage: 3, repair: 2 } }, { id: 'hc_volume', label: 'Lack of Volume / Flatness', points: { volume: 3, scalp_oily: 1 } }, { id: 'hc_growth', label: 'Thinning / Scalp Health', points: { scalp_care: 3 } }, { id: 'hc_color', label: 'Color Fading', points: { color: 3 } }] },
            { id: 'hair_styling', text: 'How often do you use hot tools?', options: [{ id: 'hs_never', label: 'Rarely or never', points: { damage: -1 } }, { id: 'hs_sometimes', label: '1-2 times a week', points: { damage: 1, heat: 1 } }, { id: 'hs_often', label: 'Almost every day', points: { damage: 3, heat: 3 } }] },
            { id: 'hair_product_type', text: 'What type of product are you looking to discover?', options: [{ id: 'hp_shampoo', label: 'Shampoo & Cleansers', filterTarget: 'Shampoo' }, { id: 'hp_treatment', label: 'Masks & Serums', filterTarget: 'Treatment' }, { id: 'hp_styling', label: 'Styling & Heat Prep', filterTarget: 'Styling' }, { id: 'hp_any', label: 'Show me everything', filterTarget: 'All' }] }
        ]
    },
    products: {
        skin: [
            {
                id: 'doppelt_1',
                name: "Mandelic Acid Serum",
                category: "Serum",
                desc: "The iconic multi-tasking serum to help address acne, uneven skin tone, and visible signs of aging.",
                price: 1450,
                priceRange: "₹1,200 - ₹1,800",
                image: "images/doppelt_serum.png",
                traits: ["acne", "aging", "dullness", "pigmentation", "all"],
                ingredients: ["Mandelic Acid", "Lactic Acid", "Hyaluronic Acid"],
                howToUse: "Apply 3-4 drops to clean skin in the evening. Mild tingling is normal.",
                rating: 4.9,
                reviews: 215
            },
            {
                id: 'doppelt_2',
                name: "A.G.E. Advanced Eye",
                category: "Treatment",
                desc: "An anti-wrinkle eye cream that improves the appearance of dark circles, puffiness, and crow’s feet.",
                price: 4800,
                priceRange: "₹4,200 - ₹5,500",
                image: "images/doppelt_eye.png",
                traits: ["aging", "dry", "normal", "all"],
                ingredients: ["Peptides", "Caffeine", "Optical Diffusers"],
                howToUse: "Gently pat a small amount around the orbital bone twice daily.",
                rating: 4.7,
                reviews: 180
            },
            {
                id: 'doppelt_3',
                name: "Acne Spray Treatment",
                category: "Treatment",
                desc: "Glytone's Acne Spray Treatment contains salicylic acid as the main ingredient for the treatment of acne, specifically formulated for hard-to-reach areas.",
                price: 1150,
                priceRange: "₹950 - ₹1,300",
                image: "images/doppelt_spray.png",
                traits: ["acne", "oily", "body", "all"],
                ingredients: ["Salicylic Acid 2%", "Water", "Alcohol"],
                howToUse: "Spray on affected areas 1-3 times daily as needed. Let dry.",
                rating: 4.5,
                reviews: 95
            },
            {
                id: 'doppelt_4',
                name: "Advanced RGN-6",
                category: "Moisturizer",
                desc: "Advanced RGN-6 is a potent skin regenerating cream inspired by laser regeneration science, designed to help with signs of aging.",
                price: 6500,
                priceRange: "₹6,000 - ₹7,500",
                image: "images/doppelt_rgn.png",
                traits: ["aging", "dry", "normal", "sensitive", "all"],
                ingredients: ["Growth Factors", "Ceramides", "Vitamin E"],
                howToUse: "Apply a thin layer to the face and neck daily after cleansing and serums.",
                rating: 5.0,
                reviews: 60
            },
            {
                id: 's1',
                name: 'Hydrating Milky Cleanser',
                category: 'Cleanser',
                desc: 'A gentle, non-foaming cleanser that melts away impurities while soothing sensitive skin. Formulated without harsh sulfates, this rich milky texture ensures your skin barrier remains fully intact.',
                price: 750,
                priceRange: "₹650 - ₹850",
                image: 'images/cleanser_hydrating.png',
                traits: ['dry', 'sensitive', 'normal', 'redness', 'all'],
                ingredients: ['Ceramides', 'Oat Extract', 'Hyaluronic Acid', 'Glycerin'],
                howToUse: 'Massage 1-2 pumps onto damp skin in circular motions. Rinse thoroughly with lukewarm water. Use AM and PM.',
                rating: 4.8,
                reviews: 142
            },
            {
                id: 's2',
                name: 'Salicylic Acid Foaming Cleanser',
                category: 'Cleanser',
                desc: 'Deeply cleanses pores and reduces excess oil without stripping the skin barrier. Utilizing micro-exfoliation technology, this daily wash visibly reduces the appearance of blackheads.',
                price: 850,
                priceRange: "₹750 - ₹950",
                image: 'images/cleanser_foaming.png',
                traits: ['oily', 'acne', 'textured', 'all'],
                ingredients: ['2% BHA', 'Zinc', 'Niacinamide', 'Tea Tree Water'],
                howToUse: 'Lather a small amount in wet hands. Massage onto face for 60 seconds, focusing on congested areas. Rinse thoroughly.',
                rating: 4.6,
                reviews: 215
            },
            {
                id: 's3',
                name: 'Vitamin C Brightening Serum',
                category: 'Serum',
                desc: 'A potent 15% vitamin C formula that boosts radiance and fades dark spots over time. The antioxidant complex shields against environmental aggressors to prevent further pigmentation.',
                price: 699,
                priceRange: "₹640 - ₹750",
                image: 'images/serum_vitaminc.png',
                traits: ['dullness', 'pigmentation', 'aging', 'normal', 'all'],
                ingredients: ['15% L-Ascorbic Acid', 'Vitamin E', 'Ferulic Acid', 'Licorice Root'],
                howToUse: 'Apply 3-5 drops to clean, dry skin every morning. Follow with moisturizer and an SPF of 30 or higher.',
                rating: 4.9,
                reviews: 630
            },
            {
                id: 's4',
                name: 'Rich Ceramide Repair Cream',
                category: 'Moisturizer',
                desc: 'Luxurious thick cream designed to rescue compromised skin barriers and provide all-day moisture. Acts as a protective shield against bitter cold and harsh wind.',
                price: 950,
                priceRange: "₹850 - ₹1,100",
                image: 'images/cream_repair.png',
                traits: ['dry', 'sensitive', 'redness', 'all'],
                ingredients: ['Ceramide Complex', 'Squalane', 'Shea Butter', 'Panthenol'],
                howToUse: 'Warm a dime-sized amount between fingers and gently press into the face and neck as the final step of your nighttime routine.',
                rating: 4.9,
                reviews: 840
            },
            {
                id: 's5',
                name: 'Retinol Night Renewal Serum',
                category: 'Serum',
                desc: 'An encapsulated retinol to gently smooth fine lines, firm skin, and refine texture while you sleep. Slowly releases active ingredients to minimize irritation.',
                price: 799,
                priceRange: "₹699 - ₹850",
                image: 'images/serum_retinol.png',
                traits: ['aging', 'textured', 'normal', 'all'],
                ingredients: ['0.5% Encapsulated Retinol', 'Matrixyl Peptides', 'Centella Asiatica'],
                howToUse: 'Apply a pea-sized amount to dry face 2-3 nights a week. Gradually increase frequency as tolerance builds.',
                rating: 4.7,
                reviews: 412
            },
            {
                id: 's6',
                name: 'Niacinamide Clarifying Toner',
                category: 'Serum',
                desc: 'A refreshing daily splash that dramatically reduces the appearance of pores and balances sebum. Instantly mattifies while providing a rush of lightweight hydration.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/toner_niacinamide.png',
                traits: ['oily', 'acne', 'normal', 'all'],
                ingredients: ['5% Niacinamide', 'Witch Hazel', 'Green Tea Extract'],
                howToUse: 'After cleansing, saturate a cotton pad and sweep across face and neck, or pat directly into skin with your hands.',
                rating: 4.5,
                reviews: 198
            },
            {
                id: 's7',
                name: 'Mineral Sunscreen SPF 50',
                category: 'Sunscreen',
                desc: 'Broad spectrum protection that is non-nano, reef-safe, and blends flawlessly without a nasty white cast. Features a sheer, powdery finish perfect under makeup.',
                price: 399,
                priceRange: "₹350 - ₹450",
                image: 'images/sunscreen_mineral.png',
                traits: ['all', 'sensitive', 'dry', 'normal', 'oily'],
                ingredients: ['20% Zinc Oxide', 'Aloe Vera', 'Green Tea Antioxidants'],
                howToUse: 'Apply a generous amount (two fingers length) every morning as the final step of your skincare routine. Reapply every 2 hours if outdoors.',
                rating: 4.6,
                reviews: 550
            },
            {
                id: 's8',
                name: 'AHA/BHA Peeling Solution',
                category: 'Treatment',
                desc: 'A powerful weekly wash-off treatment for dramatic re-texturizing and deep pore clearance. Instantly dissolves dead skin cells for a glass-skin effect.',
                price: 600,
                priceRange: "₹540 - ₹680",
                image: 'images/exfoliant_peel.png',
                traits: ['textured', 'dullness', 'acne', 'oily', 'all'],
                ingredients: ['10% Lactic Acid', '2% Salicylic Acid', 'Glycolic Acid', 'Tasmanian Pepperberry'],
                howToUse: 'Use only PM. Apply evenly across dry, clean face. Leave on for no more than 10 minutes. Rinse thoroughly. Do not exceed 1-2 times per week.',
                rating: 4.8,
                reviews: 921
            },
            {
                id: 's9',
                name: 'Dot & Key Daily Moisturizer',
                category: 'Moisturizer',
                desc: 'A lightweight daily moisturizer. Less hydrating, so may not fully address severe dry skin concerns. Not designed for acne-prone skin; limited anti-acne benefit.',
                price: 495,
                priceRange: "₹450 - ₹550",
                image: 'images/dot_and_key.png',
                traits: ['normal', 'oily', 'all'],
                ingredients: ['Vitamin C', 'Niacinamide', 'Ceramides'],
                howToUse: 'Apply an even layer to cleansed face and neck daily.',
                rating: 4.2,
                reviews: 85
            },
            /* --- NEW CLEANSERS --- */
            {
                id: 's10',
                name: 'CeraVe Hydrating Cleanser',
                category: 'Cleanser',
                desc: 'A non-foaming lotion that cleanses, hydrates and helps restore the protective skin barrier with three essential ceramides and hyaluronic acid.',
                price: 750,
                priceRange: "₹680 - ₹850",
                image: 'images/cerave_bottle.png',
                traits: ['dry', 'normal', 'sensitive', 'all'],
                ingredients: ['Ceramides', 'Hyaluronic Acid'],
                howToUse: 'Wet skin with lukewarm water. Massage cleanser into skin in a gentle, circular motion. Rinse.',
                rating: 4.8,
                reviews: 1250
            },
            {
                id: 's11',
                name: 'CeraVe Foaming Cleanser',
                category: 'Cleanser',
                desc: 'A gentle, foaming gel that deeply cleanses, removes excess oil and refreshes the skin without over-stripping or leaving it tight and dry.',
                price: 1150,
                priceRange: "₹1,050 - ₹1,250",
                image: 'images/blue_foam_pump.png',
                traits: ['oily', 'normal', 'acne', 'all'],
                ingredients: ['Ceramides', 'Niacinamide', 'Hyaluronic Acid'],
                howToUse: 'Lather in hands and massage onto wet skin. Rinse thoroughly.',
                rating: 4.7,
                reviews: 980
            },
            {
                id: 's12',
                name: 'CeraVe Gel Cleanser (88ml)',
                category: 'Cleanser',
                desc: 'Travel-friendly gentle cleanser that effectively removes dirt, oil and makeup while maintaining the skin barrier.',
                price: 350,
                priceRange: "₹280 - ₹450",
                image: 'images/cerave_bottle.png',
                traits: ['all', 'normal', 'sensitive'],
                ingredients: ['Ceramides', 'Essential Lipids'],
                howToUse: 'Gentle enough for daily use, morning and evening.',
                rating: 4.5,
                reviews: 430
            },
            {
                id: 's13',
                name: 'CeraVe Acne Foaming Cleanser',
                category: 'Cleanser',
                desc: 'Formulated with 4% benzoyl peroxide to help clear acne and prevent new breakouts from forming.',
                price: 1450,
                priceRange: "₹1,350 - ₹1,650",
                image: 'images/blue_foam_pump.png',
                traits: ['acne', 'oily'],
                ingredients: ['4% Benzoyl Peroxide', 'Ceramides'],
                howToUse: 'Apply a dime-sized amount to wet skin and massage in for 1-2 minutes. Rinse well.',
                rating: 4.4,
                reviews: 620
            },
            /* --- NEW SERUMS --- */
            {
                id: 's14',
                name: 'The Ordinary Niacinamide Serum',
                category: 'Serum',
                desc: 'High-strength vitamin and mineral blemish formula with 10% pure Niacinamide and 1% Zinc PCA.',
                price: 600,
                priceRange: "₹540 - ₹680",
                image: 'images/minimalist_dropper.png',
                traits: ['oily', 'acne', 'textured', 'all'],
                ingredients: ['Niacinamide 10%', 'Zinc PCA 1%'],
                howToUse: 'Apply to entire face morning and evening before heavier creams.',
                rating: 4.9,
                reviews: 2150
            },
            {
                id: 's15',
                name: 'Minimalist Niacinamide Serum',
                category: 'Serum',
                desc: 'A minimalist approach to blemish-free skin. Reduces excess sebum and fades post-acne marks.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/minimalist_dropper.png',
                traits: ['oily', 'acne', 'pigmentation', 'all'],
                ingredients: ['Niacinamide', 'Zinc'],
                howToUse: 'Pat a small amount into skin after cleansing. Follow with moisturizer.',
                rating: 4.7,
                reviews: 840
            },
            {
                id: 's16',
                name: 'The Derma Co Niacinamide Serum',
                category: 'Serum',
                desc: 'Effective formulation for controlling acne and clearing the skin of blemishes and acne marks.',
                price: 349,
                priceRange: "₹290 - ₹390",
                image: 'images/plum_dropper.png',
                traits: ['acne', 'pigmentation', 'oily'],
                ingredients: ['10% Niacinamide'],
                howToUse: 'Apply twice daily for best results.',
                rating: 4.5,
                reviews: 560
            },
            /* --- NEW MOISTURIZERS --- */
            {
                id: 's17',
                name: 'Cetaphil Moisturising Cream',
                category: 'Moisturizer',
                desc: 'Intense and lasting moisture to replenish sensitive, very dry skin. clinically proven to provide immediate and long-term relief.',
                price: 1100,
                priceRange: "₹950 - ₹1,250",
                image: 'images/cetaphil_tub.png',
                traits: ['dry', 'sensitive', 'all'],
                ingredients: ['Sweet Almond Oil', 'Vitamin E'],
                howToUse: 'Apply liberally as often as needed or as directed by a physician.',
                rating: 4.9,
                reviews: 1850
            },
            {
                id: 's18',
                name: 'Cetaphil Moisturising Lotion',
                category: 'Moisturizer',
                desc: 'Lightweight hydration for every skin type. Non-greasy moisturizing for beautiful skin.',
                price: 750,
                priceRange: "₹650 - ₹850",
                image: 'images/cerave_bottle.png',
                traits: ['normal', 'all', 'sensitive'],
                ingredients: ['Glycerin', 'Panthenol'],
                howToUse: 'Apply daily to face and body for hydration.',
                rating: 4.8,
                reviews: 1100
            },
            /* --- NEW SUNSCREENS --- */
            {
                id: 's19',
                name: 'Minimalist SPF 50 Sunscreen',
                category: 'Sunscreen',
                desc: 'Broad spectrum SPF 50 PA++++ that is invisible on skin. Lightweight and non-greasy.',
                price: 399,
                priceRange: "₹340 - ₹450",
                image: 'images/sunscreen_tube.png',
                traits: ['all', 'normal', 'oily'],
                ingredients: ['Octocrylene', 'Avobenzone'],
                howToUse: 'Apply as the last step in your skin routine, 15 minutes before sun exposure.',
                rating: 4.6,
                reviews: 740
            },
            {
                id: 's20',
                name: 'Minimalist Light Fluid SPF 50',
                category: 'Sunscreen',
                desc: 'Ultra-light fluid sunscreen with SPF 50. Water resistant and perfect for active days.',
                price: 499,
                priceRange: "₹450 - ₹550",
                image: 'images/sunscreen_tube.png',
                traits: ['all', 'oily', 'normal'],
                ingredients: ['Modern Filters'],
                howToUse: 'Shake well before use.',
                rating: 4.7,
                reviews: 320
            },
            /* --- NEW TREATMENTS --- */
            {
                id: 's21',
                name: 'Deconstruct Clearing Serum',
                category: 'Treatment',
                desc: 'Targets acne marks and spots effectively with Alpha Arbutin and Niacinamide.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/plum_dropper.png',
                traits: ['acne', 'pigmentation'],
                ingredients: ['Alpha Arbutin', 'Niacinamide'],
                howToUse: 'Massage 2-3 drops on clean skin. Use daily at night.',
                rating: 4.3,
                reviews: 210
            },
            {
                id: 's22',
                name: 'Clinikally NIA Serum',
                category: 'Treatment',
                desc: 'Advanced niacinamide serum for glowing, clear skin and refined texture.',
                price: 850,
                priceRange: "₹750 - ₹950",
                image: 'images/minimalist_dropper.png',
                traits: ['pigmentation', 'dullness', 'all'],
                ingredients: ['Niacinamide'],
                howToUse: 'Apply every morning for radiance.',
                rating: 4.8,
                reviews: 145
            },
            {
                id: 's23',
                name: 'CeraVe Hydrating Cleanser (Nykaa)',
                category: 'Cleanser',
                desc: 'Value pack of the classic hydrating cleanser. Restores barrier while removing impurities.',
                price: 350,
                priceRange: "₹300 - ₹450",
                image: 'images/cerave_bottle.png',
                traits: ['dry', 'normal', 'all'],
                ingredients: ['Ceramides', 'Hyaluronic Acid'],
                howToUse: 'Use AM and PM.',
                rating: 4.6,
                reviews: 50
            },
            {
                id: 's24',
                name: 'Plum Niacinamide Serum',
                category: 'Serum',
                desc: '10% Niacinamide + Rice Water. Brightens and clears skin texture.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/plum_dropper.png',
                traits: ['dullness', 'textured', 'all'],
                ingredients: ['Rice Water', 'Niacinamide'],
                howToUse: 'Apply 2-3 drops after cleansing.',
                rating: 4.4,
                reviews: 210
            },
            {
                id: 's25',
                name: 'Cetaphil DAM Lotion',
                category: 'Moisturizer',
                desc: 'Daily Advance Ultra Hydrating Lotion for dry to extra dry skin.',
                price: 299,
                priceRange: "₹250 - ₹350",
                image: 'images/cetaphil_tub.png',
                traits: ['dry', 'sensitive'],
                ingredients: ['Glycerin', 'Macadamia Nut Oil'],
                howToUse: 'Apply daily.',
                rating: 4.8,
                reviews: 890
            },
            {
                id: 's26',
                name: 'Plum Niacinamide Sunscreen',
                category: 'Sunscreen',
                desc: 'Blemish-fighting sunscreen with Niacinamide for oily and acne-prone skin.',
                price: 399,
                priceRange: "₹350 - ₹450",
                image: 'images/sunscreen_tube.png',
                traits: ['acne', 'oily'],
                ingredients: ['SPF 50', 'Niacinamide'],
                howToUse: 'Apply 15 minutes before sun exposure.',
                rating: 4.2,
                reviews: 150
            },
            {
                id: 's27',
                name: 'Pilgrim Niacinamide Serum',
                category: 'Serum',
                desc: 'Alpha Arbutin & Niacinamide serum for skin brightening and spot reduction.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/plum_dropper.png',
                traits: ['pigmentation', 'dullness', 'all'],
                ingredients: ['Niacinamide', 'Alpha Arbutin'],
                howToUse: 'Apply twice daily.',
                rating: 4.3,
                reviews: 95
            },
            {
                id: 's28',
                name: 'Cetaphil Hydration Cream',
                category: 'Moisturizer',
                desc: 'Optimal Hydration Daily Glow Cream that provides 48 hour hydration.',
                price: 1150,
                priceRange: "₹950 - ₹1,250",
                image: 'images/cetaphil_tub.png',
                traits: ['dry', 'normal', 'sensitive', 'all'],
                ingredients: ['Hyaluronic Acid', 'Vitamin E'],
                howToUse: 'Apply every morning.',
                rating: 4.8,
                reviews: 420
            },
            {
                id: 's29',
                name: 'Minimalist SPF 60 Sunscreen',
                category: 'Sunscreen',
                desc: 'High protection UVA/UVB sunscreen for intense sun exposure.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/sunscreen_tube.png',
                traits: ['all'],
                ingredients: ['Titanium Dioxide', 'Zinc Oxide'],
                howToUse: 'Apply generously.',
                rating: 4.7,
                reviews: 180
            },
            {
                id: 's30',
                name: 'Mamaearth Skin Correct Serum',
                category: 'Treatment',
                desc: 'Reduces acne marks and tightens pores with Niacinamide and Ginger Extract.',
                price: 499,
                priceRange: "₹450 - ₹599",
                image: 'images/plum_dropper.png',
                traits: ['acne', 'textured'],
                ingredients: ['Ginger Extract', 'Niacinamide'],
                howToUse: 'Apply daily.',
                rating: 4.2,
                reviews: 560
            }
        ],
        hair: [
            {
                id: 'h1',
                name: 'Clarifying Scalp Serum',
                category: 'Treatment',
                desc: 'An exfoliant for your scalp that breaks down product buildup, balances oil, and promotes healthy growth. Essential for those using heavy styling products or dry shampoos.',
                price: 750,
                priceRange: "₹650 - ₹850",
                image: 'images/hair_serum_scalp.png',
                traits: ['scalp_oily', 'scalp_care', 'volume', 'all'],
                ingredients: ['Salicylic Acid', 'Peppermint Oil', 'Niacinamide', 'Rosemary Extract'],
                howToUse: 'Part hair into sections. Apply directly to the scalp and massage in 10 minutes before showering. Wash out with shampoo.',
                rating: 4.7,
                reviews: 210
            },
            {
                id: 'h2',
                name: 'Volumizing Peptide Shampoo',
                category: 'Shampoo',
                desc: 'A lightweight cleanser that plumps hair strands from the root for maximum lift and density. Color-safe and entirely sulfate-free.',
                price: 650,
                priceRange: "₹550 - ₹780",
                image: 'images/hair_shampoo_volume.png',
                traits: ['volume', 'straight', 'scalp_normal', 'scalp_oily', 'all'],
                ingredients: ['Biotin', 'Amaranth Peptides', 'Panthenol'],
                howToUse: 'Massage into wet hair to build a rich lather. Rinse thoroughly and follow with your preferred conditioner.',
                rating: 4.4,
                reviews: 312
            },
            {
                id: 'h3',
                name: 'Hydrating Argan Hair Mask',
                category: 'Treatment',
                desc: 'A deeply restorative deep conditioner that breathes life back into dry, coarse, or damaged hair. Seals the cuticle tightly for insane slip and shine.',
                price: 650,
                priceRange: "₹550 - ₹850",
                image: 'images/hair_mask_argan.png',
                traits: ['damage', 'dry', 'curly', 'coily', 'frizz', 'all'],
                ingredients: ['Pure Argan Oil', 'Shea Butter', 'Keratin Amino Acids'],
                howToUse: 'Apply a generous scoop to damp hair after shampooing. Leave on for 5-15 minutes, then rinse with cold water.',
                rating: 4.9,
                reviews: 1045
            },
            {
                id: 'h4',
                name: 'Anti-Frizz Smoothing Oil',
                category: 'Styling',
                desc: 'A weightless oil blend that locks out humidity, seals flyaways, and delivers glass-like shine without ever making hair look greasy.',
                price: 450,
                priceRange: "₹399 - ₹550",
                image: 'images/hair_oil_frizz.png',
                traits: ['frizz', 'wavy', 'curly', 'coily', 'damage', 'all'],
                ingredients: ['Jojoba Oil', 'Squalane', 'Silicone Alternatives'],
                howToUse: 'Apply 1-2 drops to palms, rub together, and smooth over mid-lengths and ends of dry or damp hair.',
                rating: 4.8,
                reviews: 780
            },
            {
                id: 'h5',
                name: 'Leave-In Heat Protectant',
                category: 'Styling',
                desc: 'A fine mist that detangles, hydrates, and protects hair up to 450°F from hot tools. Crucial for daily blow-drying or flat-ironing.',
                price: 399,
                priceRange: "₹350 - ₹480",
                image: 'images/hair_spray_protect.png',
                traits: ['heat', 'damage', 'color', 'straight', 'wavy', 'all'],
                ingredients: ['Grape Seed Extract', 'Wheat Protein', 'Vitamin E'],
                howToUse: 'Spray evenly through towel-dried hair before blow-drying, or onto dry hair before using curling wands or straighteners.',
                rating: 4.6,
                reviews: 455
            },
            /* --- NEW SHAMPOOS --- */
            {
                id: 'h6',
                name: 'Olaplex No.4 Shampoo',
                category: 'Shampoo',
                desc: 'Highly concentrated hair repair shampoo that hydrates and nourishes hair. Repairs and maintains bonds within the hair.',
                price: 2950,
                priceRange: "₹2,700 - ₹3,200",
                image: 'images/blue_foam_pump.png',
                traits: ['damage', 'dry', 'color', 'all'],
                ingredients: ['Patented Bond Building Chemistry'],
                howToUse: 'Use every time you wash your hair. Massage into wet hair, lather, and rinse.',
                rating: 4.9,
                reviews: 4500
            },
            {
                id: 'h7',
                name: 'Olaplex Clarifying Shampoo',
                category: 'Shampoo',
                desc: 'Deeply cleanses the hair and scalp to remove product buildup, oil, and hard water minerals.',
                price: 2950,
                priceRange: "₹2,700 - ₹3,200",
                image: 'images/cerave_bottle.png',
                traits: ['scalp_oily', 'volume', 'all'],
                ingredients: ['Broad Spectrum Clarifying System'],
                howToUse: 'Use once a week in place of your regular shampoo.',
                rating: 4.8,
                reviews: 1200
            },
            /* --- NEW HAIR SERUMS --- */
            {
                id: 'h8',
                name: 'Minimalist Hair Growth Serum',
                category: 'Treatment',
                desc: 'A powerful hair growth serum that uses 3% Redensyl and 2% Anagain to reduce hair fall and promote growth.',
                price: 799,
                priceRange: "₹680 - ₹899",
                image: 'images/minimalist_dropper.png',
                traits: ['scalp_care', 'volume', 'all'],
                ingredients: ['Redensyl', 'Anagain', 'Procapil'],
                howToUse: 'Apply a few drops directly to the scalp every night.',
                rating: 4.7,
                reviews: 2100
            },
            {
                id: 'h9',
                name: 'Minimalist Frizz Control Serum',
                category: 'Styling',
                desc: 'A lightweight serum that tames frizz and flyaways while providing heat protection and shine.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/plum_dropper.png',
                traits: ['frizz', 'heat', 'all'],
                ingredients: ['Squalane', 'Coconut Oil'],
                howToUse: 'Apply to damp or dry hair before styling.',
                rating: 4.6,
                reviews: 890
            },
            {
                id: 'h10',
                name: 'WishCare Hair Growth Serum',
                category: 'Treatment',
                desc: 'Natural and effective hair growth serum with caffeine and biotin to strengthen hair roots.',
                price: 699,
                priceRange: "₹600 - ₹850",
                image: 'images/minimalist_dropper.png',
                traits: ['scalp_care', 'volume'],
                ingredients: ['Caffeine', 'Biotin'],
                howToUse: 'Massage into scalp daily.',
                rating: 4.5,
                reviews: 430
            },
            {
                id: 'h11',
                name: 'Olaplex Blonde Shampoo',
                category: 'Shampoo',
                desc: 'Purple shampoo that cleanses, tones, and repairs while keeping hair hydrated from roots to ends.',
                price: 2950,
                priceRange: "₹2,700 - ₹3,200",
                image: 'images/blue_foam_pump.png',
                traits: ['color', 'damage', 'dry'],
                ingredients: ['Bis-Aminopropyl Diglycol Dimaleate'],
                howToUse: 'Apply to wet hair. Lather fully and let process for 1-3 minutes.',
                rating: 4.9,
                reviews: 810
            },
            {
                id: 'h12',
                name: 'Minimalist Anti-Dandruff Hair Serum',
                category: 'Treatment',
                desc: 'Targeted scalp treatment with Piroctone Olamine to eliminate dandruff and soothe itchiness.',
                price: 499,
                priceRange: "₹450 - ₹599",
                image: 'images/minimalist_dropper.png',
                traits: ['scalp_dry', 'scalp_care'],
                ingredients: ['Piroctone Olamine', 'Salicylic Acid'],
                howToUse: 'Apply to clean, dry scalp and massage.',
                rating: 4.6,
                reviews: 240
            },
            {
                id: 'h13',
                name: 'Minimalist Bond Repair Serum',
                category: 'Treatment',
                desc: 'Pre-wash treatment that repairs hair bonds and reduces breakage from the first use.',
                price: 599,
                priceRange: "₹540 - ₹680",
                image: 'images/plum_dropper.png',
                traits: ['damage', 'frizz', 'dry', 'all'],
                ingredients: ['Maleic Acid', 'Trans-Glutaminase'],
                howToUse: 'Apply to dry hair before washing. Leave for 15 minutes.',
                rating: 4.8,
                reviews: 670
            }
        ]
    }
};
